
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iyenloyjwftmehkigxsh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5ZW5sb3lqd2Z0bWVoa2lneHNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1MzUwNDYsImV4cCI6MjA1NTExMTA0Nn0.ta9o_jPm2ogRJ7fjyelCZIt3AIWBr7WP1849DLbjvEQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
